#ifndef S2HTML_EVENT_H
#define S2HTML_EVENT_H

/* Event property types */
#define USER_HEADER_FILE        1   // User-defined header file ("file.h")
#define STD_HEADER_FILE         2   // Standard header file (<stdio.h>)
#define RES_KEYWORD_DATA        3   // Reserved keyword (data type)
#define RES_KEYWORD_NON_DATA    4   // Reserved keyword (non-data type)

/* Increased buffer size to handle large tokens in big files */
#define PEVENT_DATA_SIZE        8192

/* Event types generated by parser */
typedef enum
{
    PEVENT_NULL,                    // No valid event
    PEVENT_PREPROCESSOR_DIRECTIVE,  // #include, #define etc.
    PEVENT_RESERVE_KEYWORD,         // Keywords like int, if, return
    PEVENT_NUMERIC_CONSTANT,        // Numbers like 123
    PEVENT_STRING,                  // String literals "text"
    PEVENT_HEADER_FILE,             // Header files <stdio.h>
    PEVENT_REGULAR_EXP,             // Normal text
    PEVENT_SINGLE_LINE_COMMENT,     //  comment
    PEVENT_MULTI_LINE_COMMENT,      // /* comment */
    PEVENT_ASCII_CHAR,              // Character constants 'a'
    PEVENT_EOF                      // End of file
} pevent_e;

/* Structure to store parsed event data */
typedef struct
{
    pevent_e type;                  // Type of event
    int property;                   // Additional property info
    int length;                     // Length of data
    char data[PEVENT_DATA_SIZE];    // Parsed string data
} pevent_t;

/********** Function Prototype **********/

// Main parser function to extract next event from file
pevent_t *get_parser_event(FILE *fp);

#endif
/* End of file */